[versions]
minSdk = "21"
compileSdk = "36"
kotlin = "2.3.10"
agp = "8.13.2" # https://maven.google.com/web/index.html?q=gradle.plugin#com.android.library:com.android.library.gradle.plugin
androidx-compose-ui = "1.10.4"   # https://developer.android.com/jetpack/androidx/releases/compose-ui
androidx-compose-ui-material3 = "1.4.0"
androidx-compose-material = "1.7.8" # https://developer.android.com/jetpack/androidx/releases/compose-material
compose-multiplatform = "1.10.2" # https://github.com/JetBrains/compose-multiplatform/releases
androidx-appcompat = "1.7.1"
androidx-activity = "1.12.4"  # https://developer.android.com/jetpack/androidx/releases/activity
androidx-savedstate = "1.4.0"  # https://developer.android.com/jetpack/androidx/releases/savedstate
androidx-lifecycle = "2.10.0"  # https://developer.android.com/jetpack/androidx/releases/lifecycle
paparazzi = "2.0.0-alpha04" # https://github.com/cashapp/paparazzi/releases
mavenPublish = "0.36.0" # https://github.com/vanniktech/gradle-maven-publish-plugin/releases
dokka = "2.1.0" # https://github.com/Kotlin/dokka/releases
junit = "4.13.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }

[libraries]
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-ui" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-ui-material3" }
compose-materialIcons = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose-material" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity"}
androidx-savedstate = { module = "androidx.savedstate:savedstate", version.ref = "androidx-savedstate" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle"}

junit = { module = "junit:junit", version.ref = "junit" }
